  const handleSort = (column) => { const nextDirection = sortColumn === column && sortDirection === 'asc' ? 'desc' : 'asc'; setSortColumn(column); setSortDirection(nextDirection); setStatus(`Sorted by ${SORT_COLUMN_LABELS[column]}, ${nextDirection === 'asc' ? 'ascending' : 'descending'}.`); };
  const sortButtonLabel = (column) => { const label = SORT_COLUMN_LABELS[column]; if (sortColumn !== column) return `Sort by ${label}`; const current = sortDirection === 'asc' ? 'ascending' : 'descending'; const next = sortDirection === 'asc' ? 'descending' : 'ascending'; return `${label}, sorted ${current}. Activate to sort ${next}.`; };
  const ariaSortValue = (column) => (sortColumn === column ? (sortDirection === 'asc' ? 'ascending' : 'descending') : undefined);
  const sortGlyph = (column) => (sortColumn === column ? (sortDirection === 'asc' ? '▲' : '▼') : '');
  const selectAllVisible = () => { const filePaths = visibleItems.filter((item) => !item.directory).map((item) => item.path); setSelectedFiles((current) => { const next = new Set(current); filePaths.forEach((p) => next.add(p)); return next; }); setStatus(filePaths.length ? `Selected ${filePaths.length} visible ${filePaths.length === 1 ? 'file' : 'files'} for the agent.` : 'No visible files to select.'); };
  const collectAllFilePaths = async () => { const cache = { ...children }; const newlyLoaded = {}; const paths = []; const failedPaths = []; const visit = async (dirPath) => { let entries = cache[dirPath]; if (!entries) { try { const response = await axios.get(`${host}/project/list`, { params: { path: dirPath } }); entries = Array.isArray(response.data?.entries) ? response.data.entries : []; } catch { failedPaths.push(dirPath); return; } cache[dirPath] = entries; newlyLoaded[dirPath] = entries; } for (const entry of entries) { const path = entryPath(entry, dirPath); if (!path) continue; if (isDirectory(entry)) await visit(path); else paths.push(path); } }; await visit('.'); if (Object.keys(newlyLoaded).length) setChildren((current) => ({ ...current, ...newlyLoaded })); return { paths, failedPaths }; };
  const selectAllFiles = async () => { if (selectingAllFiles) return; setSelectingAllFiles(true); setError(''); setStatus('Scanning the entire project for files.'); try { const { paths, failedPaths } = await collectAllFilePaths(); let finalCount = 0; setSelectedFiles((current) => { const next = new Set(current); paths.forEach((p) => next.add(p)); finalCount = next.size; return next; }); const failureNote = failedPaths.length ? ` ${failedPaths.length} ${failedPaths.length === 1 ? 'folder' : 'folders'} could not be read and ${failedPaths.length === 1 ? 'was' : 'were'} skipped.` : ''; setStatus(`Selected ${finalCount} ${finalCount === 1 ? 'file' : 'files'} across the entire project.${failureNote}`); if (failedPaths.length) setError('Some folders could not be listed while selecting all files. The selection may be incomplete.'); } catch (err) { const message = err?.response?.data?.error || err?.message || 'Unable to select all project files.'; setError(message); setStatus('Unable to select all project files.'); } finally { setSelectingAllFiles(false); } };
  const clearSelection = () => {
    setSelectedFiles(new Set());
    setLastSelectedPath(null);
    // Clear both explorer-local persistence and the shared Chat permission
    // list so a just-cleared selection cannot be restored by a remount.
    try {
      localStorage.setItem(`${storageKey}:selected`, JSON.stringify([]));
      sessionStorage.setItem(`${storageKey}:selected`, JSON.stringify([]));
      localStorage.setItem('ai-terminal-chat:allowed-paths', JSON.stringify([]));
    } catch {}
    setStatus('Cleared agent file selection.');
  };
  const useSelectedFiles = async () => { const paths = Array.from(selectedFiles); if (!paths.length) { setStatus('No files are selected for the agent.'); onUseSelectedFiles?.([]); return; } setStatus(`Reading ${paths.length} selected ${paths.length === 1 ? 'file' : 'files'} for the agent.`); setError(''); try { const files = []; for (const path of paths) { const response = await axios.get(`${host}/project/read`, { params: { path } }); files.push({ path: response.data?.path || path, content: response.data?.contents ?? response.data?.content ?? '' }); } onUseSelectedFiles?.(files); setStatus(`${files.length} ${files.length === 1 ? 'file' : 'files'} supplied to the agent.`); } catch (err) { const message = err?.response?.data?.error || err?.message || 'Unable to read selected files.'; setError(message); setStatus('Unable to supply selected files to the agent.'); } };