import { createRequire } from "node:module";
import { writeSync } from "node:fs";
const log = (s) => { try { writeSync(2, s + "\n"); } catch {} };
const require = createRequire(import.meta.url);
log("1 require koffi");
const koffi = require("koffi");
log("2 koffi loaded");
const ntdll = koffi.load("ntdll.dll");
log("3 ntdll loaded");
const kernel32 = koffi.load("kernel32.dll");
log("4 kernel32 loaded");
const crt = koffi.load("ucrtbase.dll");
log("5 ucrtbase loaded");
const UnicodeString = koffi.struct("UNICODE_STRING", { Length: "uint16", MaximumLength: "uint16", Buffer: "void *" });
const ObjectAttributes = koffi.struct("OBJECT_ATTRIBUTES", { Length: "uint32", RootDirectory: "void *", ObjectName: "void *", Attributes: "uint32", SecurityDescriptor: "void *", SecurityQualityOfService: "void *" });
const IoStatusBlock = koffi.struct("IO_STATUS_BLOCK", { Status: "void *", Information: "uintptr" });
log("6 structs defined, sizeof OA=" + koffi.sizeof(ObjectAttributes) + " US=" + koffi.sizeof(UnicodeString) + " IOSB=" + koffi.sizeof(IoStatusBlock));
const NtCreateFile = ntdll.func("NtCreateFile", "long", ["void *","uint32","void *","void *","void *","uint32","uint32","uint32","uint32","void *","uint32"]);
log("7 NtCreateFile bound");
const getOsFHandle = crt.func("_get_osfhandle", "intptr", ["int"]);
const openOsFHandle = crt.func("_open_osfhandle", "int", ["intptr", "int"]);
const CloseHandle = kernel32.func("CloseHandle", "int", ["uintptr"]);
log("8 crt funcs bound");
const { mkdtempSync, openSync, constants } = await import("node:fs");
const { join } = await import("node:path");
const { tmpdir } = await import("node:os");
const p = mkdtempSync(join(tmpdir(), "crashstep-"));
const pfd = openSync(p, constants.O_RDONLY | constants.O_DIRECTORY);
log("9 pfd=" + pfd);
const h = getOsFHandle(pfd);
log("10 parentHandle=" + h);
const nameU16 = Buffer.from("out.txt", "utf16le");
const usPtr = koffi.alloc(UnicodeString, 1);
koffi.encode(usPtr, UnicodeString, { Length: nameU16.length, MaximumLength: nameU16.length, Buffer: nameU16 });
log("11 us encoded");
const oaPtr = koffi.alloc(ObjectAttributes, 1);
koffi.encode(oaPtr, ObjectAttributes, { Length: koffi.sizeof(ObjectAttributes), RootDirectory: h, ObjectName: usPtr, Attributes: 0x1040, SecurityDescriptor: null, SecurityQualityOfService: null });
log("12 oa encoded");
const iosb = koffi.alloc(IoStatusBlock, 1);
koffi.encode(iosb, IoStatusBlock, { Status: null, Information: 0 });
const handleOut = koffi.alloc("void *", 1);
log("13 allocs done, calling NtCreateFile");
const status = NtCreateFile(handleOut, 0x80000000 | 0x40000000 | 0x00100000, oaPtr, iosb, null, 0x80, 7, 3, 0x40 | 0x20, null, 0);
log("14 status=" + status + " unsigned=" + (status >>> 0));
const handle = koffi.decode(handleOut, "void *");
log("15 handle=" + handle);
const fd = openOsFHandle(h === handle ? 0 : handle, 2 | 0x8000);
log("16 fd=" + fd);
if (fd >= 0) CloseHandle(handle);
log("DONE");
