import { createRequire } from "node:module";
import { writeSync } from "node:fs";
const log = (s) => { try { writeSync(2, s + "\n"); } catch {} };
const require = createRequire(import.meta.url);
const koffi = require("koffi");
const kernel32 = koffi.load("kernel32.dll");
const crt = koffi.load("ucrtbase.dll");
const msvcrt = koffi.load("msvcrt.dll");
const getU = crt.func("_get_osfhandle", "intptr", ["int"]);
const getM = msvcrt.func("_get_osfhandle", "intptr", ["int"]);
const { openSync, writeFileSync, mkdtempSync, fstatSync, closeSync } = await import("node:fs");
const { join } = await import("node:path");
const { tmpdir } = await import("node:os");
const p = mkdtempSync(join(tmpdir(), "varb-"));
log("B1 mkdtemp done");
writeFileSync(join(p, "x.txt"), "y");
log("B2 write done");
const fd = openSync(join(p, "x.txt"), 0);
log("B3 fd=" + fd);
const st = fstatSync(fd);
log("B4 fstat ok size=" + st.size);
log("B5 calling ucrt _get_osfhandle");
const hu = getU(fd);
log("B6 ucrt handle=" + hu);
log("DONE-B");
