import { createRequire } from "node:module";
import { writeSync } from "node:fs";
const log = (s) => { try { writeSync(2, s + "\n"); } catch {} };
const require = createRequire(import.meta.url);
const koffi = require("koffi");
const ntdll = koffi.load("ntdll.dll");
const kernel32 = koffi.load("kernel32.dll");
const crt = koffi.load("ucrtbase.dll");
const GetCurrentProcessId = kernel32.func("GetCurrentProcessId", "uint32", []);
log("A1 kernel32 call pid=" + GetCurrentProcessId());
const getH = crt.func("_get_osfhandle", "intptr", ["int"]);
log("A2 bound, calling with fd 0");
log("A3 fd0 handle=" + getH(0));
log("A4 fd1=" + getH(1));
log("A5 fd2=" + getH(2));
const { openSync, writeFileSync, mkdtempSync } = await import("node:fs");
const { join } = await import("node:path");
const { tmpdir } = await import("node:os");
const p = mkdtempSync(join(tmpdir(), "vara-"));
writeFileSync(join(p, "x.txt"), "y");
const fd = openSync(join(p, "x.txt"), 0);
log("A6 file fd=" + fd + " handle=" + getH(fd));
log("DONE-A");
