import { createRequire } from "node:module";
import { writeSync } from "node:fs";
const log = (s) => { try { writeSync(2, s + "\n"); } catch {} };
const require = createRequire(import.meta.url);
const koffi = require("koffi");
const node = koffi.load(process.execPath);
const uvGet = node.func("uv_get_osfhandle", "void *", ["int"]);
const uvOpen = node.func("uv_open_osfhandle", "int", ["void *"]);
const ntdll = koffi.load("ntdll.dll");
const kernel32 = koffi.load("kernel32.dll");
const UnicodeString = koffi.struct("UNICODE_STRING", { Length: "uint16", MaximumLength: "uint16", Buffer: "void *" });
const ObjectAttributes = koffi.struct("OBJECT_ATTRIBUTES", { Length: "uint32", RootDirectory: "void *", ObjectName: "void *", Attributes: "uint32", SecurityDescriptor: "void *", SecurityQualityOfService: "void *" });
const IoStatusBlock = koffi.struct("IO_STATUS_BLOCK", { Status: "void *", Information: "uintptr" });
const NtCreateFile = ntdll.func("NtCreateFile", "long", ["void *","uint32","void *","void *","void *","uint32","uint32","uint32","uint32","void *","uint32"]);
const RtlNtStatusToDosError = ntdll.func("RtlNtStatusToDosError", "uint32", ["long"]);
const CloseHandle = kernel32.func("CloseHandle", "int", ["uintptr"]);
const { openSync, readFileSync, closeSync, writeSync: fsWrite, readSync, constants, mkdtempSync, existsSync } = await import("node:fs");
const { join } = await import("node:path");
const { tmpdir } = await import("node:os");
const p = mkdtempSync(join(tmpdir(), "vare-"));
log("E1 project=" + p);
const pfd = openSync(p, constants.O_RDONLY | constants.O_DIRECTORY);
log("E2 dir fd=" + pfd + " O_DIRECTORY=" + constants.O_DIRECTORY);
const ph = uvGet(pfd);
log("E3 parent handle via uv=" + ph);
const nameU16 = Buffer.from("out.bin", "utf16le");
const usPtr = koffi.alloc(UnicodeString, 1);
koffi.encode(usPtr, UnicodeString, { Length: nameU16.length, MaximumLength: nameU16.length, Buffer: nameU16 });
const oaPtr = koffi.alloc(ObjectAttributes, 1);
koffi.encode(oaPtr, ObjectAttributes, { Length: koffi.sizeof(ObjectAttributes), RootDirectory: ph, ObjectName: usPtr, Attributes: 0x1040, SecurityDescriptor: null, SecurityQualityOfService: null });
const iosb = koffi.alloc(IoStatusBlock, 1);
koffi.encode(iosb, IoStatusBlock, { Status: null, Information: 0 });
const handleOut = koffi.alloc("void *", 1);
const status = NtCreateFile(handleOut, 0xC0100000, oaPtr, iosb, null, 0x80, 7, 3, 0x40 | 0x20, null, 0);
log("E4 NtCreateFile status=" + (status >>> 0) + " dos=" + RtlNtStatusToDosError(status));
if ((status >>> 0) !== 0) process.exit(1);
const ch = koffi.decode(handleOut, "void *");
log("E5 child handle=" + ch);
const cfd = uvOpen(ch);
log("E6 child fd via uv_open=" + cfd);
const payload = Buffer.concat([Buffer.from("line1\nline2\n"), Buffer.from([0x00, 0x0a, 0x1a, 0xff]), Buffer.from("end\n")]);
fsWrite(cfd, payload);
log("E7 node writeSync ok");
closeSync(cfd);
log("E8 closeSync ok");
const disk = readFileSync(join(p, "out.bin"));
log("E9 on-disk=" + JSON.stringify(disk.toString("hex")));
log("E10 binary-safe=" + (disk.equals(payload)));
// also read-back through the handle-path fd for the security.ts readFile path
const pfd2 = openSync(p, constants.O_RDONLY | constants.O_DIRECTORY);
const ph2 = uvGet(pfd2);
const us2 = koffi.alloc(UnicodeString, 1); const n2 = Buffer.from("out.bin", "utf16le");
koffi.encode(us2, UnicodeString, { Length: n2.length, MaximumLength: n2.length, Buffer: n2 });
const oa2 = koffi.alloc(ObjectAttributes, 1);
koffi.encode(oa2, ObjectAttributes, { Length: koffi.sizeof(ObjectAttributes), RootDirectory: ph2, ObjectName: us2, Attributes: 0x1040, SecurityDescriptor: null, SecurityQualityOfService: null });
const iosb2 = koffi.alloc(IoStatusBlock, 1); koffi.encode(iosb2, IoStatusBlock, { Status: null, Information: 0 });
const hout2 = koffi.alloc("void *", 1);
const st2 = NtCreateFile(hout2, 0x80100000, oa2, iosb2, null, 0x80, 7, 1, 0x40 | 0x20 | 0x200000, null, 0);
log("E11 open-existing status=" + (st2 >>> 0));
const cfd2 = uvOpen(koffi.decode(hout2, "void *"));
const buf = Buffer.alloc(64); const n = readSync(cfd2, buf, 0, 64, null);
log("E12 readSync n=" + n + " data=" + JSON.stringify(buf.subarray(0, n).toString("hex")));
closeSync(cfd2); closeSync(pfd2); closeSync(pfd);
log("DONE-E binary=" + disk.equals(payload));

